version = 1

exclude_patterns = [
  "# dependencies",
  "**/node_modules/**",
  "/.pnp",
  ".pnp.js",
  "# Build files",
  "*.min.js",
  "*.min.css",
  "sw.js",
  "*.js.map",
  "# Packages",
  "src/scripts/libraries/**",
  "# misc",
  ".DS_Store",
  ".env.local",
  ".env.development.local",
  ".env.test.local",
  ".env.production.local",
  ".vscode",
  "# workbox",
  "workbox-config.js",
  "src/serviceWorker/**",
  "# Visual Studio Code",
  ".vscode/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true